# Generated by Django 2.0.5 on 2018-06-28 13:34

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20180628_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pound',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
